### PR TITLE
Remove `/unity-ggjj/OldProjectFiles`

### PR DESCRIPTION
**Pull request by ViMaSter**
## Summary
Removes all assets (scripts, images and scenes) from the `/OldProjectFiles`-folder. That's... everything.

From what I've seen, all functionality in there has been implemented and should be safe to remove.

## Testing instructions
Make sure all scenes still play properly, test suites succeed and there are no remaining dependencies to any of the deleted files.

## Additional information

- `[ ]` Changes UI
- `[ ]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:

### CODE REVIEW

**Review by notexplosive — DISMISSED** [review]

**Review by PhoebeMitchell — CHANGES_REQUESTED** [review]
Finally someone did it :D
That said, it seems to MainMenu background (POWER_HOUR_SET_HQ.png) was caught in the crossfire. Not sure if we're getting anything to replace this, so I think we should keep it for now.

Some other things that are part of the old build but not in OldProjectFiles and could be deleted:

- Assets/Prefabs/Characters
- Assets/Prefabs/Evidence
- Assets/Prefabs/Others (except SubStory, for now)
- Assets/Images/SpeechBoxes

Images in Assets/Images/UI that can be deleted (I think)

- Back_1
- Back_2
- Choice_Box
- Confirm_1
- Confirm_2
- Court Record Left
- Court Record Right
- Court Record
- Court_Record_1
- Court_Record_2
- Evidence Board
- Evidence_01
- Evidence_1
- Evidence_2
- Present_1
- Present_2
- Press_1
- Press_2
- Profiles_1
- Profiles_2
- Left Arrow
- Right Arrow
- GeneralTextBox
- TextBox

**Comment by ViMaSter** [comment]
> Finally someone did it :D That said, it seems to MainMenu background (POWER_HOUR_SET_HQ.png) was caught in the crossfire. Not sure if we're getting anything to replace this, so I think we should keep it for now.

Good catch! Only ran the Cross Examination scene and was kinda hoping Unity would throw build errors if things are missing; turns out it didn't. 👀  
Added it to [Assets/Images/BackgroundsAndForegrounds/MainMenu/PowerHourSet.png](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/468e79a668ee972d3468d7d5f00c66a426f253e3/unity-ggjj/Assets/Images/BackgroundsAndForegrounds/MainMenu/PowerHourSet.png).

> Some other things that are part of the old build but not in OldProjectFiles and could be deleted:
> * Assets/Prefabs/Characters
> * Assets/Prefabs/Evidence
> * Assets/Prefabs/Others (except SubStory, for now)
> * Assets/Images/SpeechBoxes

Removed them and tested a few scenes, so far everything looks good to me, feel free to double-check though!

> Images in Assets/Images/UI that can be deleted (I think)
> [...]

Checked the .meta-files for these by hand and they all seemed unused, so I've removed them too.

**Review by lyndsiWilliams — APPROVED** [review]
So many files! Thanks for the cleanup! Tests pass and game runs locally ✅

**Review by PhoebeMitchell — APPROVED** [review]
ZAP!

**Pull request merged**
