### PR TITLE
Feature/66 fading in and out actions

### PR DESCRIPTION
**Pull request by PhoebeMitchell**
## Summary

Implements the FADE_IN and FADE_OUT actions. This is achieved using the existing FadeToImageController which now implements ITransition (instead of being a child of TransitionController). This modifies the approach for fade ins and outs in by changing the current system of storing settings in a scriptable object in favour of setting the settings on Image components directly.

## Before/after screenshots and/or animated gif

fadedemo

## Testing instructions

Open "Inky-Test Scene", set dialogue controller's narrative script to "FadeInOutDemo" and enter play mode.

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature
- `[]` Removes existing feature
- `[x]` Has associated resource: 
  
#66

### CODE REVIEW

**Review by lyndsiWilliams — DISMISSED** [review]
Looks good to me!

**Review by JuiceGrape — DISMISSED** [review]

**Review by lyndsiWilliams — DISMISSED** [review]
m a r g e  i t ✨

**Review by JuiceGrape — DISMISSED** [review]

**Review by lyndsiWilliams — APPROVED** [review]
Wooo no more conflicts with Marge! Get it in quick! 🏃

**Review by JuiceGrape — APPROVED** [review]
mobile approving powers

**Pull request merged**
