### PR TITLE
Feature/121 studio lovelies unity splash

### LINKED ISSUE #121: Studio Lovelies Unity Splash
## Description
Unity allows you to set a logo to play after the Unity splash-screen. Set this to the Studio Lovelies logo. Maybe communicate with the artists or the higher ups and ask which logo they would like.

## Acceptance Criteria

This story will be finished when the exported build has a Studio Lovelies splash when it starts up.

### PR DESCRIPTION
**Pull request by PhoebeMitchell**
## Summary

Implements the Studio Lovelies splash screen. A requested feature was that it randomly played an alternate splash, so the feature is implemented in its own scene, as opposed to Unity's splash screen options.

## Before/after screenshots and/or animated gif

splash3

## Testing instructions

Play the "Splash" scene. Does the splash play? Does it automatically continue to the menu scene. Export the game, and check the splash plays properly in the exported build.

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource: 
  
closes #121

### CODE REVIEW

**Comment by ViMaSter** [comment]
`Splash` scene works and looks good to me!

Regarding the full startup sequence: We could technically completely remove the "Unity logo" from it and limit it to the `Splash` scene, since our Build Server is building with my Unity Pro licence. 
image
I think I would actually prefer that. Any opinions on it?

<sub>You must die.</sub>

**Review by ViMaSter — DISMISSED** [review]

**Review by ViMaSter — APPROVED** [review]
Feels weird to approve a branch I contributed changes to, but since that change has literally been changing a `1` to `0` , I'd argue I can still approve the rest. : D

**Comment by ViMaSter** [comment]
Merged `develop` into it so the workflow file is updated and uses the Pro license to check if the automated build actually has no splash screen now. 👀

**Review by lyndsiWilliams — APPROVED** [review]
It's beautiful! 👏

**Pull request merged**
